name: stock_manager_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.1
  go_router: ^14.0.2
  equatable: ^2.0.5
  dio: ^5.4.0
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.0
  firebase_crashlytics: ^3.3.5
  freezed_annotation: ^2.4.1
  syncfusion_flutter_charts: ^25.1.42+1
  flutter_image_compress: ^2.1.0
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.8
  riverpod_annotation:
  data_table_2: ^2.5.12
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.2
  riverpod_lint:
  riverpod_generator:
  custom_lint:
  json_serializable:
  analyzer:

flutter:
  uses-material-design: true
